apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinsapp
  namespace: devops-ns
spec:
  selector:
    matchLabels:
      app: jenkinsapp
  template:
    metadata:
      labels:
        app: jenkinsapp
    spec:
      containers:
      - name: jenkinscontainer
        image: jenkins/jenkins:lts
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: myvolume
          mountPath: /var/jenkins_home  
      volumes:
      - name: myvolume
        PersistentVolumeClaim: 
        - ClaimName: jenkinspvc
      
